# Generated by Django 5.2.3 on 2025-08-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='संकायको नाम')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='संकायको बारेमा')),
            ],
            options={
                'verbose_name': 'संकाय',
                'verbose_name_plural': 'संकायहरू',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='फाइलको शीर्षक')),
                ('file', models.FileField(upload_to='syllabus_pdfs/', verbose_name='PDF फाइल')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='अपलोड मिति')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_files', to='syllabus.faculty', verbose_name='संकाय')),
            ],
            options={
                'verbose_name': 'सिलेबस फाइल',
                'verbose_name_plural': 'सिलेबस फाइलहरू',
                'ordering': ['faculty__name', 'title'],
            },
        ),
    ]
